package dev.zanderp.opencfmoto

import android.content.Context

/**
 * Translates text which is assembled at runtime (status messages, route details and legacy enum
 * labels). Static screen copy lives in values/ and values-es/; this bridge keeps the remaining
 * dynamic UI bilingual without changing protocol/log strings.
 */
fun Context.uiText(text: String): String {
    val language = resources.configuration.locales[0]?.language.orEmpty()
    if (language != "es" || text.isBlank()) return text

    SPANISH_EXACT[text]?.let { return it }

    val replacements = listOf(
        Regex("""^Invalid GPX: (.+)$""") to "GPX no válido: $1",
        Regex("""^Export failed: (.+)$""") to "Error al exportar: $1",
        Regex("""^Share failed: (.+)$""") to "Error al compartir: $1",
        Regex("""^Import failed: (.+)$""") to "Error al importar: $1",
        Regex("""^Couldn't share report: (.+)$""") to "No se pudo compartir el informe: $1",
        Regex("""^Camera bind failed: (.+)$""") to "No se pudo iniciar la cámara: $1",
        Regex("""^Added (.+)$""") to "Se agregó $1",
        Regex("""^Selected (.+)$""") to "Se seleccionó $1",
        Regex("""^Remove (.+)\\?$""") to "¿Quitar $1?",
        Regex("""^Couldn't open (.+)$""") to "No se pudo abrir $1",
        Regex("""^(.+) is missing or disabled$""") to "$1 no está instalada o está deshabilitada",
        Regex("""^(.+) is no longer available$""") to "$1 ya no está disponible",
        Regex("""^(.+) ready$""") to "$1 lista",
        Regex("""^Update (.+)$""") to "Actualizar $1",
        Regex("""^Searching \"(.+)\" on the dash$""") to "Buscando «$1» en el tablero",
        Regex("""^Sent \"(.+)\" to Android Auto$""") to "Se envió «$1» a Android Auto",
        Regex("""^Downloading offline map for \"(.+)\"…$""") to "Descargando el mapa sin conexión de «$1»…",
        Regex("""^Offline map: (.+)$""") to "Mapa sin conexión: $1",
        Regex("""^Clear cached bike tiles \\((.+)\\)$""") to "Borrar mapas guardados de la moto ($1)",
        Regex("""^Map theme: (.+)$""") to "Tema del mapa: $1",
        Regex("""^Double-tap delay: (.+)$""") to "Demora del doble toque: $1",
        Regex("""^Hold delay: (.+)$""") to "Demora al mantener presionado: $1",
        Regex("""^Video quality: (.+)$""") to "Calidad de video: $1",
        Regex("""^Screen fit: (.+)$""") to "Ajuste de pantalla: $1",
        Regex("""^Power mode: (.+)$""") to "Modo de energía: $1",
        Regex("""^Resolution: (.+)$""") to "Resolución: $1",
        Regex("""^Bike profile: (.+)$""") to "Perfil de moto: $1",
        Regex("""^Wi‑Fi transport: (.+)$""") to "Transporte Wi‑Fi: $1",
        Regex("""^Auto-connect (.+)$""") to "Conexión automática $1",
        Regex("""^Auto-recovery (.+)$""") to "Recuperación automática $1",
        Regex("""^Trip logging (.+)$""") to "Registro de viajes $1",
        Regex("""^(.+) \\(applies next connect\\)$""") to "$1 (se aplica en la próxima conexión)",
        Regex("""^To (.+)$""") to "Hacia $1",
        Regex("""^GPS… · navigate to (.+)$""") to "GPS… · navegar hacia $1",
        Regex("""^Building there & back to (.+)…$""") to "Creando ida y vuelta hacia $1…",
        Regex("""^Saved (.+) to favorites$""") to "Se guardó $1 en favoritos",
        Regex("""^Marker added for (.+)$""") to "Se agregó un marcador para $1",
        Regex("""^Deleted (.+)$""") to "Se eliminó $1",
        Regex("""^Finding (.+) nearby…$""") to "Buscando $1 cerca…",
        Regex("""^No (.+) found nearby$""") to "No se encontró $1 cerca",
        Regex("""^(\\d+) (.+) nearby$""") to "$1 $2 cerca",
        Regex("""^(\\d+) places$""") to "$1 lugares",
        Regex("""^Route · (.+)$""") to "Ruta · $1",
        Regex("""^Apps are parked-only\\. Current speed is about (.+) km/h\\.$""") to
            "Las aplicaciones sólo se pueden usar con la moto estacionada. Velocidad actual aproximada: $1 km/h.",
        Regex("""^Applied: (.+) \\(handlebar → AA on\\)$""") to
            "Aplicado: $1 (manillar → Android Auto activado)",
        Regex("""^Connect to (.+)$""") to "Conectar con $1",
        Regex("""^(\\d+) ride · (.+)$""") to "$1 recorrido · $2",
        Regex("""^(\\d+) rides · (.+)$""") to "$1 recorridos · $2",
        Regex("""^GPS fix(.+)$""") to "Señal GPS$1",
        Regex("""^Nav · (.+)$""") to "Navegación · $1",
        Regex("""^Arrived · (.+)$""") to "Llegaste · $1",
        Regex("""^GPS… · navigate to (.+)$""") to "GPS… · navegar hacia $1",
        Regex("""^GPS… · (.+) track$""") to "GPS… · recorrido de $1",
        Regex("""^(.+) · (.+) to (.+) · avg (.+)$""") to "$1 · $2 hasta $3 · prom. $4",
        Regex("""^(.+) · free ride · avg (.+)$""") to "$1 · recorrido libre · prom. $2",
        Regex("""^Roadside POI ready \\((\\d+)\\)$""") to "Puntos de interés de la ruta listos ($1)",
        Regex("""^Navigate to parked · (.+)$""") to "Navegar al estacionamiento · $1",
        Regex("""^Navigate Home · (.+)$""") to "Navegar a Casa · $1",
        Regex("""^Roadside POI: (\\d+) \\(fuel, parking, food…\\)$""") to
            "Puntos de interés de la ruta: $1 (combustible, estacionamiento, comida…)",
        Regex("""^Not installed: (.+)$""") to "No instaladas: $1",
        Regex("""^(.+) · (.+) · avg (.+) · max (.+)$""") to "$1 · $2 · prom. $3 · máx. $4",
    )
    for ((pattern, replacement) in replacements) {
        if (pattern.matches(text)) return pattern.replace(text, replacement)
    }
    return text
}

private val SPANISH_EXACT = mapOf(
    "AA controls need a bike connection" to "Los controles de Android Auto necesitan conexión con la moto",
    "Already free ride" to "Ya estás en recorrido libre",
    "App settings" to "Configuración de la aplicación",
    "Apply" to "Aplicar",
    "Balanced (recommended)" to "Equilibrado (recomendado)",
    "Balanced — 24 fps (recommended)" to "Equilibrado — 24 fps (recomendado)",
    "Battery saver — 20 fps (coolest)" to "Ahorro de batería — 20 fps (más frío)",
    "Builds a shareable report with diagnostics + recent log (secrets redacted unless enabled in Setup)." to
        "Crea un informe para compartir con diagnósticos y el registro reciente (los datos sensibles se ocultan salvo que se habiliten en Configuración).",
    "Cached bike tiles cleared" to "Se borraron los mapas guardados de la moto",
    "Camera permission required" to "Se necesita permiso para usar la cámara",
    "Cancel" to "Cancelar",
    "Centered on GPS" to "Centrado en el GPS",
    "Checking for update…" to "Buscando actualizaciones…",
    "Choose an app other than OpenCfMoto" to "Elegí una aplicación distinta de OpenCfMoto",
    "Circuit" to "Circuito",
    "Clear" to "Borrar",
    "Clear cluster preset?" to "¿Borrar la configuración del mando?",
    "Close & retry" to "Cerrar y reintentar",
    "Confirm the bike is parked" to "Confirmá que la moto está estacionada",
    "Connect to the bike first" to "Primero conectate con la moto",
    "Could not load map — try again from Map hub" to "No se pudo cargar el mapa; probá otra vez desde Mapas",
    "Could not read file" to "No se pudo leer el archivo",
    "Couldn't open Android Auto settings" to "No se pudo abrir la configuración de Android Auto",
    "Couldn't open app settings" to "No se pudo abrir la configuración de la aplicación",
    "Couldn't open donate link" to "No se pudo abrir el enlace de donación",
    "Couldn't open download link" to "No se pudo abrir el enlace de descarga",
    "Couldn't open link" to "No se pudo abrir el enlace",
    "Couldn't open overlay settings" to "No se pudo abrir la configuración de superposición",
    "Couldn't open the overlay permission screen" to "No se pudo abrir el permiso para mostrarse sobre otras aplicaciones",
    "Couldn't open the Play Store" to "No se pudo abrir Play Store",
    "Couldn't read that image" to "No se pudo leer esa imagen",
    "Couldn't start GPS" to "No se pudo iniciar el GPS",
    "Dash view" to "Vista del tablero",
    "Delete" to "Eliminar",
    "Delete trip?" to "¿Eliminar el viaje?",
    "Deleted" to "Eliminado",
    "Dismiss" to "Cerrar",
    "Done" to "Listo",
    "Downloading roadside POI…" to "Descargando puntos de interés de la ruta…",
    "Empty file" to "El archivo está vacío",
    "Favorite saved" to "Favorito guardado",
    "Fill — edge to edge (crops a little)" to "Llenar — de borde a borde (recorta un poco)",
    "Fit — no cropping (black bars)" to "Ajustar — sin recorte (barras negras)",
    "Follow on" to "Seguimiento activado",
    "Free pan" to "Mover libremente",
    "Free ride" to "Recorrido libre",
    "Fullscreen — press Back to exit" to "Pantalla completa; presioná Atrás para salir",
    "GPS error" to "Error de GPS",
    "GPS is off" to "El GPS está apagado",
    "GPX has no track points or waypoints" to "El GPX no tiene puntos de recorrido ni destinos",
    "GPX loaded — tap Open GPX on map" to "GPX cargado; tocá Abrir GPX en el mapa",
    "GPX ready — Open on map, or Project to bike when connected." to
        "GPX listo; abrilo en el mapa o proyectalo en la moto cuando esté conectada.",
    "Home saved" to "Casa guardada",
    "Home set" to "Casa establecida",
    "Home set here" to "Casa establecida aquí",
    "I am parked" to "Estoy estacionado",
    "Import" to "Importar",
    "Import settings?" to "¿Importar la configuración?",
    "Invalid QR" to "Código QR no válido",
    "Keep logs" to "Conservar registros",
    "Later" to "Más tarde",
    "Leave the shared app on screen (OpenCfMoto stays in the notification)" to
        "Dejá la aplicación compartida en pantalla (OpenCfMoto queda en la notificación)",
    "Left switch cluster" to "Mando izquierdo",
    "Location permission is required for the trip HUD" to "Se necesita permiso de ubicación para registrar el viaje",
    "Map ready — building offline routing…" to "Mapa listo; preparando la navegación sin conexión…",
    "Map UI failed to open" to "No se pudo abrir la interfaz del mapa",
    "Mark parking, find a spot, or continue free ride" to "Marcá el estacionamiento, buscá un lugar o continuá el recorrido libre",
    "Marker added" to "Marcador agregado",
    "Marker saved" to "Marcador guardado",
    "Missing dependencies" to "Faltan componentes necesarios",
    "Need a GPS fix for nearby POI" to "Se necesita señal GPS para buscar lugares cercanos",
    "Need a GPS fix to mark parking" to "Se necesita señal GPS para marcar el estacionamiento",
    "Need a GPS fix to pick an area" to "Se necesita señal GPS para elegir un área",
    "Need a GPS fix to set Home" to "Se necesita señal GPS para establecer Casa",
    "Need GPS for a circuit" to "Se necesita GPS para crear un circuito",
    "Need GPS for nearby POI" to "Se necesita GPS para buscar lugares cercanos",
    "No bike saved — opening on phone map instead" to "No hay una moto guardada; se abrirá el mapa en el teléfono",
    "No circuit found" to "No se encontró un circuito",
    "No compatible app picker is available" to "No hay un selector de aplicaciones compatible",
    "No GPS" to "Sin GPS",
    "no GPS" to "sin GPS",
    "No GPS for parking" to "No hay GPS para marcar el estacionamiento",
    "No GPS to set Home" to "No hay GPS para establecer Casa",
    "No GPS yet — wait for a fix" to "Todavía no hay GPS; esperá la señal",
    "No Home set — long-press map or use Set Home" to "Casa no está establecida; mantené presionado el mapa o usá Establecer casa",
    "No results" to "Sin resultados",
    "No rides" to "Sin recorridos",
    "No road route · straight line" to "Sin ruta por caminos · línea recta",
    "Official CFMoto app is in the way" to "La aplicación oficial de CFMoto está interfiriendo",
    "Open OpenCfMoto on phone to type" to "Abrí OpenCfMoto en el teléfono para escribir",
    "Open Settings → Apps → OpenCfMoto → Display over other apps" to
        "Abrí Configuración → Aplicaciones → OpenCfMoto → Mostrar sobre otras aplicaciones",
    "Open Settings ▸ Network ▸ VPN" to "Abrí Configuración ▸ Red ▸ VPN",
    "Open Setup" to "Abrir Configuración",
    "Open Setup to finish prerequisites" to "Abrí Configuración para completar los requisitos",
    "Overview · north up" to "Vista general · norte arriba",
    "Pad fullscreen — screen stays on. Press Back to exit." to
        "Control en pantalla completa; la pantalla permanecerá encendida. Presioná Atrás para salir.",
    "Parked spot cleared" to "Se borró el lugar de estacionamiento",
    "Parking marked" to "Estacionamiento marcado",
    "Pick a destination, then Circuit (there & back)" to "Elegí un destino y después Circuito (ida y vuelta)",
    "Pick a place away from you, then Circuit" to "Elegí un lugar alejado y después Circuito",
    "Preset cleared" to "Configuración predefinida borrada",
    "Recent & favorites" to "Recientes y favoritos",
    "Recentered" to "Centrado nuevamente",
    "Recovered after a crash" to "Recuperación después de un cierre inesperado",
    "Remove" to "Quitar",
    "Rename bike" to "Cambiar nombre de la moto",
    "Report a problem" to "Informar un problema",
    "Reset" to "Restablecer",
    "Reset to defaults" to "Se restablecieron los valores predeterminados",
    "Reset to defaults?" to "¿Restablecer los valores predeterminados?",
    "Ride recording saved" to "Registro del recorrido guardado",
    "Route overview · north up" to "Vista general de la ruta · norte arriba",
    "Routing…" to "Calculando la ruta…",
    "Save" to "Guardar",
    "Save this pin — open it later to navigate" to "Guardá este marcador para navegar hasta él más tarde",
    "Saved (applies next connect)" to "Guardado (se aplica en la próxima conexión)",
    "Screen sharing could not be started" to "No se pudo iniciar la proyección de pantalla",
    "Search for a place or tap a category" to "Buscá un lugar o elegí una categoría",
    "Searching…" to "Buscando…",
    "Set that place's address below" to "Ingresá abajo la dirección de ese lugar",
    "Share" to "Compartir",
    "Share Logs" to "Compartir registros",
    "Single-app mirror needs Android 14+. Whole screen will be used." to
        "La proyección de una sola aplicación necesita Android 14 o posterior. Se usará toda la pantalla.",
    "Skip" to "Omitir",
    "Smoother — less data/latency" to "Más fluido — menos datos y demora",
    "Smooth — 30 fps (most battery)" to "Fluido — 30 fps (más batería)",
    "Snap · back on track" to "Ajustado · de vuelta en la ruta",
    "Some permissions are still off — use “App settings” to enable them." to
        "Todavía faltan permisos; usá «Configuración de la aplicación» para habilitarlos.",
    "Start Android Auto first" to "Primero iniciá Android Auto",
    "Stretch — fills, slight distortion" to "Estirar — llena la pantalla con una leve distorsión",
    "Suggestions…" to "Sugerencias…",
    "That app cannot be launched" to "No se puede iniciar esa aplicación",
    "The selected app did not provide a launch activity" to "La aplicación elegida no se puede iniciar",
    "The selected app was lost. Choose it again." to "Se perdió la aplicación elegida. Volvé a seleccionarla.",
    "There & back · returning home" to "Ida y vuelta · regreso a casa",
    "This forgets its pairing, photo and settings. You can re-scan the dash QR later." to
        "Esto borra el emparejamiento, la foto y la configuración. Más adelante podés escanear de nuevo el QR del tablero.",
    "Tip: download offline maps first if cellular will drop on the bike Wi‑Fi" to
        "Consejo: descargá antes los mapas sin conexión si la red móvil se corta al usar el Wi‑Fi de la moto",
    "Trip has no GPS points" to "El viaje no tiene puntos GPS",
    "Trip not found" to "No se encontró el viaje",
    "Turn on GPS/Location to record" to "Activá GPS/Ubicación para registrar",
    "Turn on Wi‑Fi" to "Activar Wi‑Fi",
    "Turn on “Display over other apps” for seamless resume" to
        "Activá «Mostrar sobre otras aplicaciones» para reanudar sin interrupciones",
    "Type a destination first" to "Primero escribí un destino",
    "Type a place name" to "Escribí el nombre de un lugar",
    "Type a place to search on the map" to "Escribí un lugar para buscarlo en el mapa",
    "Type here — results show on the bike" to "Escribí aquí; los resultados se muestran en la moto",
    "Type on your phone…" to "Escribí en el teléfono…",
    "VPN is blocking the bike" to "La VPN está bloqueando la conexión con la moto",
    "VPN settings" to "Configuración de VPN",
    "Wi‑Fi settings" to "Configuración de Wi‑Fi",
    "You're up to date (or offline)" to "La aplicación está actualizada (o no hay conexión)",
    "Auto — adapts to heat & signal" to "Automático — se adapta a la temperatura y la señal",
    "Auto — match your bike (recommended)" to "Automático — coincide con tu moto (recomendado)",
    "Auto — from bike screen" to "Automático — según la pantalla de la moto",
    "Sharper — more data" to "Más nítido — usa más datos",
    "Landscape · 800×480" to "Horizontal · 800×480",
    "Landscape · 1280×720 (HD)" to "Horizontal · 1280×720 (HD)",
    "Portrait · 720×1280" to "Vertical · 720×1280",
    "Portrait · 1080×1920 (HD)" to "Vertical · 1080×1920 (HD)",
    "Off" to "Desactivado",
    "Manual size" to "Tamaño manual",
    "on" to "activada",
    "off" to "desactivada",
    "Ready" to "Lista",
    "Starting Android Auto…" to "Iniciando Android Auto…",
    "Android Auto live — joining bike…" to "Android Auto activo; conectando con la moto…",
    "Connecting to bike Wi-Fi…" to "Conectando al Wi‑Fi de la moto…",
    "Linking to dashboard…" to "Vinculando con el tablero…",
    "Connected — projecting to dash" to "Conectada; proyectando en el tablero",
    "Mirroring screen to dash" to "Proyectando la pantalla en el tablero",
    "Link dropped — reconnecting…" to "Se perdió la conexión; reconectando…",
    "Bike out of range — waiting…" to "Moto fuera de alcance; esperando…",
    "Stopped" to "Detenida",
    "Error — see logs" to "Error; consultá los registros",
    "Name (e.g. Home)" to "Nombre (por ejemplo, Casa)",
    "Address or place" to "Dirección o lugar",
    "No preset — shipped defaults / your custom map" to "Sin configuración predefinida / tu configuración personalizada",
    "Replace the current mapping for this bike? Saved places are kept." to
        "¿Reemplazar la configuración actual de esta moto? Se conservarán los lugares guardados.",
    "Do nothing" to "No hacer nada",
    "Knob forward (next item)" to "Avanzar mando (elemento siguiente)",
    "Knob back (previous item)" to "Retroceder mando (elemento anterior)",
    "Select / OK" to "Seleccionar / Aceptar",
    "Back" to "Atrás",
    "Home (app list)" to "Inicio (lista de aplicaciones)",
    "Assistant (voice)" to "Asistente (voz)",
    "D-pad up" to "Cruceta arriba",
    "D-pad down" to "Cruceta abajo",
    "D-pad left" to "Cruceta izquierda",
    "D-pad right" to "Cruceta derecha",
    "Navigate to saved place 1" to "Navegar al lugar guardado 1",
    "Navigate to saved place 2" to "Navegar al lugar guardado 2",
    "Navigate to saved place 3" to "Navegar al lugar guardado 3",
    "Backward  ◀ / ▲" to "Atrás  ◀ / ▲",
    "Forward  ▶ / ▼" to "Adelante  ▶ / ▼",
    "Select  Enter / ★" to "Seleccionar  Enter / ★",
    "Backward (hold)  ◀" to "Atrás (mantener)  ◀",
    "Forward (hold)  ▶" to "Adelante (mantener)  ▶",
    "Select (hold)  Enter / ★" to "Seleccionar (mantener)  Enter / ★",
    "Backward ×2" to "Atrás ×2",
    "Forward ×2" to "Adelante ×2",
    "Select ×2" to "Seleccionar ×2",
    "◀ left, or the ▲ volume press on non-touch dashes" to "◀ izquierda, o ▲ de volumen en tableros sin pantalla táctil",
    "▶ right, or the ▼ volume press on non-touch dashes" to "▶ derecha, o ▼ de volumen en tableros sin pantalla táctil",
    "a quick tap of the OK / ★ start button" to "un toque rápido en el botón OK / ★",
    "press and hold ◀ (track-key dashes only)" to "mantené presionado ◀ (sólo tableros con teclas de pista)",
    "press and hold ▶ (track-key dashes only)" to "mantené presionado ▶ (sólo tableros con teclas de pista)",
    "press and hold the OK / ★ button" to "mantené presionado el botón OK / ★",
    "double-tap backward within a short window" to "doble toque atrás en un intervalo corto",
    "double-tap forward within a short window" to "doble toque adelante en un intervalo corto",
    "double-tap the OK / ★ button" to "doble toque en el botón OK / ★",
    "5-way Explore (Fn / ★ / voice)" to "Mando Explore de 5 vías (Fn / ★ / voz)",
    "MODE / ENT cluster" to "Mando MODE / ENT",
    "BACK / SET diamond (limited)" to "Mando rombo BACK / SET (limitado)",
    "◀/▶ = knob (move) · ◀◀/▶▶ = D-pad ←/→ (into apps) · ★ = Select · ★★ = Back · ★ hold = Home. Singles fire immediately (no lag waiting for ×2)." to
        "◀/▶ = mando (mover) · ◀◀/▶▶ = cruceta ←/→ (entrar a aplicaciones) · ★ = Seleccionar · ★★ = Atrás · mantener ★ = Inicio. Los toques simples responden de inmediato.",
    "Same AA navigation as 5-way: knob · ×2 = D-pad ←/→ · ★★ = Back. Singles are snappy; a second tap in the window still fires ×2." to
        "La misma navegación de Android Auto que el mando de 5 vías: mando · ×2 = cruceta ←/→ · ★★ = Atrás. Los toques simples responden rápido y un segundo toque activa ×2.",
    "Snappy singles (no double-tap wait). Discrete hold / Select ×2 usually don't exist — but a hard ▲▲ / ▼▼ volume flick often coalesces into ×2 → Back / Home. On-screen pad covers anything else." to
        "Toques simples rápidos. Normalmente no hay pulsación sostenida ni Seleccionar ×2; un toque fuerte ▲▲ / ▼▼ puede convertirse en ×2 → Atrás / Inicio. El control en pantalla cubre el resto.",
    "Metric (km, m)" to "Métrico (km, m)",
    "Imperial (mi, ft)" to "Imperial (mi, pies)",
    "Dark" to "Oscuro",
    "Black" to "Negro",
    "Slate" to "Pizarra",
    "Forest" to "Bosque",
    "Fast" to "Rápida",
    "Fun" to "Divertida",
    "Auto (day / night)" to "Automático (día / noche)",
    "Day (light)" to "Día (claro)",
    "Night (dark)" to "Noche (oscuro)",
    "200 ms — snappier singles" to "200 ms — toques simples más rápidos",
    "300 ms — balanced (recommended)" to "300 ms — equilibrado (recomendado)",
    "450 ms — forgiving doubles" to "450 ms — doble toque más fácil",
    "500 ms — quicker hold" to "500 ms — pulsación sostenida más rápida",
    "600 ms — balanced (recommended)" to "600 ms — equilibrado (recomendado)",
    "800 ms — deliberate hold" to "800 ms — pulsación sostenida intencional",
    "Auto" to "Automático",
    "Detect from the bike (recommended)" to "Detectar desde la moto (recomendado)",
    "Legacy" to "Anterior",
    "CFDL16 / 450SR-style non-touch" to "CFDL16 / tipo 450SR sin pantalla táctil",
    "CRCP / sdk 0.9.23.x non-touch" to "CRCP / sdk 0.9.23.x sin pantalla táctil",
    "CFDL26 touch 720×712" to "CFDL26 táctil 720×712",
    "CFDL26 landscape touch" to "CFDL26 horizontal táctil",
    "CFDL26 portrait (handlebar-primary)" to "CFDL26 vertical (control principal desde el manillar)",
    "544×512 near-square" to "544×512 casi cuadrada",
    "Auto (from QR)" to "Automático (desde el QR)",
    "Force Wi‑Fi AP" to "Forzar punto de acceso Wi‑Fi",
    "Force Wi‑Fi Direct" to "Forzar Wi‑Fi Direct",
    "OpenCfMoto needs a few things on this phone before it can talk to your bike:\n" to
        "OpenCfMoto necesita algunos componentes en este teléfono para comunicarse con la moto:\n",
    "\n\nRecommended:" to "\n\nRecomendado:",
    "Google Android Auto" to "Google Android Auto",
    "Required to project Maps / Waze to the dash. Install it from the Play Store." to
        "Es necesario para proyectar Maps / Waze en el tablero. Instalalo desde Play Store.",
    "Google Play services" to "Servicios de Google Play",
    "Android Auto needs Play services on this phone. Install or update them from the Play Store." to
        "Android Auto necesita los servicios de Google Play. Instalalos o actualizalos desde Play Store.",
    "App permissions" to "Permisos de la aplicación",
    "Phone Wi‑Fi is off" to "El Wi‑Fi del teléfono está apagado",
    "The bike link uses Wi‑Fi. Turn Wi‑Fi on before Connect." to
        "La conexión con la moto usa Wi‑Fi. Activá Wi‑Fi antes de Conectar.",
    "Microphone (optional)" to "Micrófono (opcional)",
    "Needed for Voice / Assistant on the pad. You can grant it later when you use Voice." to
        "Se necesita para Voz / Asistente en el control. Podés habilitarlo más adelante.",
    "Display over other apps (optional)" to "Mostrar sobre otras aplicaciones (opcional)",
    "Lets OpenCfMoto relaunch Android Auto after a long stop without tapping a notification." to
        "Permite que OpenCfMoto reinicie Android Auto después de una parada larga sin tocar una notificación.",
    "Install Android Auto" to "Instalar Android Auto",
    "Install Play services" to "Instalar servicios de Google Play",
    "Grant permissions" to "Conceder permisos",
    "Enable overlay" to "Habilitar superposición",
    "OpenCfMoto joins the bike over Wi‑Fi, but your phone’s Wi‑Fi is off.\n\nTurn it on, then tap Connect again." to
        "OpenCfMoto se conecta con la moto por Wi‑Fi, pero el Wi‑Fi del teléfono está apagado.\n\nActivá Wi‑Fi y después tocá Conectar otra vez.",
    "OpenCfMoto can’t reach the bike — tap to open Wi‑Fi settings." to
        "OpenCfMoto no puede comunicarse con la moto; tocá para abrir la configuración de Wi‑Fi.",
    "Shared logs will include secrets — turn off before posting publicly" to
        "Los registros compartidos incluirán datos sensibles; desactivalo antes de publicarlos",
    "Log redaction on" to "Ocultamiento de datos sensibles activado",
    "On — passwords/serials stay in shared logs" to "Activado — contraseñas y números de serie quedan en los registros",
    "Off — passwords and serials are redacted (recommended)" to
        "Desactivado — se ocultan contraseñas y números de serie (recomendado)",
    "On — focus/knob UI so handlebar buttons work" to "Activado — interfaz de foco/mando para usar los botones del manillar",
    "Off — use the bike profile (touch dashes stay touch)" to "Desactivado — usar el perfil de la moto",
    "On — Android Auto touch UI (tap the dash)" to "Activado — interfaz táctil de Android Auto",
    "Off — use the bike profile (1000 MT‑X stays focus/knob)" to "Desactivado — usar el perfil de la moto",
    " 1. Android Auto" to " 1. Android Auto",
    "Open Android Auto" to "Abrir Android Auto",
    " 2. Permissions" to " 2. Permisos",
    "All granted" to "Todos concedidos",
    "✓ Seamless resume enabled" to "✓ Reanudación automática habilitada",
    "Enable seamless resume" to "Habilitar reanudación automática",
    "Hide logs" to "Ocultar registros",
    "Logs" to "Registros",
    "Stop" to "Detener",
    "Connect" to "Conectar",
    "No trips yet.\nRides log automatically while you project Android Auto or use the built-in Map — or record one from the Trip screen." to
        "Todavía no hay viajes.\nLos recorridos se registran automáticamente al proyectar Android Auto o usar el mapa integrado; también podés iniciar uno desde la pantalla Viaje.",
    "No rides this day.\nUse ‹ › to browse other days." to "No hay recorridos este día.\nUsá ‹ › para ver otros días.",
    "Acquiring GPS…" to "Buscando señal GPS…",
    "GPS fix" to "Señal GPS",
    "Pause" to "Pausar",
    "Start" to "Iniciar",
    "Exit" to "Salir",
    "Fullscreen" to "Pantalla completa",
    "Map preview" to "Vista previa del mapa",
    "ALT ft" to "ALT pies",
    "ALT m" to "ALT m",
    "LIMIT mph" to "LÍMITE mph",
    "LIMIT" to "LÍMITE",
    "You've arrived" to "Llegaste",
    "Search here" to "Buscar aquí",
    "Voice on" to "Voz activada",
    "Voice muted" to "Voz silenciada",
    "Heading up" to "Dirección arriba",
    "North up" to "Norte arriba",
    "Stop recording" to "Detener registro",
    "Record ride" to "Registrar recorrido",
    "GPS… · free ride" to "GPS… · recorrido libre",
    "Parking updated" to "Estacionamiento actualizado",
    "Recording ride…" to "Registrando recorrido…",
    "Can't record — check GPS / permission" to "No se puede registrar; revisá el GPS y los permisos",
    "Turn left" to "Girá a la izquierda",
    "Turn right" to "Girá a la derecha",
    "Sharp left" to "Giro cerrado a la izquierda",
    "Sharp right" to "Giro cerrado a la derecha",
    "Slight left" to "Levemente a la izquierda",
    "Slight right" to "Levemente a la derecha",
    "Bear left" to "Mantenete a la izquierda",
    "Bear right" to "Mantenete a la derecha",
    "U-turn" to "Cambio de sentido",
    "Turn around" to "Da la vuelta",
    "Roundabout" to "Rotonda",
    "Merge" to "Incorporate",
    "Keep left" to "Mantenete a la izquierda",
    "Keep right" to "Mantenete a la derecha",
    "Continue" to "Continuá",
    "Launch on bike" to "Abrir en la moto",
    "Something is holding the bike's link ports (10920-10922). Close any other CFMoto/EasyConnect app and reconnect." to
        "Otra aplicación está usando la conexión de la moto (puertos 10920-10922). Cerrá cualquier otra aplicación CFMoto/EasyConnect y volvé a conectar.",
    "Go ahead" to "Seguí derecho",
    "To route" to "Hacia la ruta",
    "Arrive" to "Llegada",
    "Screen mirroring" to "Proyección de pantalla",
    "Mirroring screen to bike" to "Proyectando la pantalla en la moto",
    "Bike button control" to "Control con botones de la moto",
    "Android Auto control" to "Control de Android Auto",
    "Bike buttons drive Android Auto — music players may briefly steal them" to
        "Los botones de la moto controlan Android Auto; el reproductor de música puede capturarlos por un momento",
    "Android Auto receiver" to "Receptor de Android Auto",
    "Tap to resume — or enable “Display over other apps” in Setup for hands-free resume" to
        "Tocá para reanudar o habilitá «Mostrar sobre otras aplicaciones» para reanudar automáticamente",
    "Tap to resume projection to the dash" to "Tocá para reanudar la proyección en el tablero",
    "Bike reconnected" to "Moto reconectada",
    "OpenCfMoto — Android Auto" to "OpenCfMoto — Android Auto",
    "Receiving Android Auto for the bike dash — tap to open" to
        "Recibiendo Android Auto para el tablero; tocá para abrir",
    "Download roadside POI (track)" to "Descargar puntos de interés de la ruta",
    "Navigate to parked bike" to "Navegar hasta la moto estacionada",
    "Clear parked spot" to "Borrar lugar de estacionamiento",
    "Update parking here" to "Actualizar estacionamiento aquí",
    "Mark parking here" to "Marcar estacionamiento aquí",
    "Navigate Home" to "Navegar a Casa",
    "Parking spot updated" to "Lugar de estacionamiento actualizado",
    "Parking spot saved" to "Lugar de estacionamiento guardado",
    "No roadside POI in corridor" to "No hay puntos de interés en el corredor de la ruta",
    "Choose an app to show on the bike" to "Elegí una aplicación para mostrar en la moto",
)
